namespace StudyVerse.Domain.Entities;

/// <summary>
/// The AI-generated study material for one <see cref="Note"/> (1:1), produced by a single
/// structured-JSON OpenAI call over the note's extracted text. The seven generated pieces are
/// stored as JSON text columns (<c>*Json</c> properties) rather than normalized into their own
/// relational tables: this content is read-heavy, always fetched and deserialized as one unit
/// (there's no query that needs e.g. "find all flashcards across notes matching X"), and it's
/// wholly owned/regenerated by the AI call rather than edited field-by-field — normalizing it
/// would add join complexity with no real benefit at this stage.
///
/// <see cref="MindMapJson"/> deserializes to a nested <c>{ topic, children: [...] }</c> tree — an
/// indented outline structure, not a visual canvas/graph. A real node-and-edge mind-map canvas
/// (positions, drag-to-rearrange, etc.) is a mobile-side rendering concern for a future pass; the
/// backend's job here is just to produce a well-structured outline the client can render as a tree.
/// </summary>
public class NoteContent
{
    public Guid Id { get; set; }

    public Guid NoteId { get; set; }

    public string Summary { get; set; } = string.Empty;

    /// <summary>JSON array of strings.</summary>
    public string KeyPointsJson { get; set; } = "[]";

    /// <summary>JSON array of <c>{ question, answer }</c>.</summary>
    public string FlashcardsJson { get; set; } = "[]";

    /// <summary>JSON array of <c>{ question, options: string[4], correctOptionIndex, explanation }</c>.</summary>
    public string McqsJson { get; set; } = "[]";

    /// <summary>JSON object: nested <c>{ topic, children: [...] }</c> outline tree.</summary>
    public string MindMapJson { get; set; } = "{}";

    /// <summary>Markdown-ish quick-revision sheet.</summary>
    public string RevisionSheet { get; set; } = string.Empty;

    /// <summary>JSON array of <c>{ term, definition }</c>.</summary>
    public string VocabularyJson { get; set; } = "[]";

    /// <summary>JSON array of <c>{ name, formula, explanation }</c>.</summary>
    public string FormulasJson { get; set; } = "[]";

    public Note? Note { get; set; }
}
