using StudyVerse.Domain.Enums;

namespace StudyVerse.Domain.Entities;

/// <summary>
/// One scheduled study session within a <see cref="StudyPlan"/>: study <see cref="Subject"/>'s
/// <see cref="Topic"/> for <see cref="DurationMinutes"/> on <see cref="ScheduledDateUtc"/>.
///
/// <see cref="OriginalScheduledDateUtc"/> is null for every task as originally generated by
/// <c>CreateStudyPlanCommandHandler</c>. It is set only by <c>MissedTaskRecoveryService</c>, on the
/// brand new replacement row it creates for a task that went overdue while still
/// <see cref="StudyPlanTaskStatus.Pending"/> — carrying forward the very first date the makeup
/// session was originally due (not just the most recent missed date, if it's been bumped more than
/// once), so the plan never loses track of how overdue something really is.
/// </summary>
public class StudyPlanTask
{
    public Guid Id { get; set; }

    public Guid PlanId { get; set; }

    public DateOnly ScheduledDateUtc { get; set; }

    public string Subject { get; set; } = string.Empty;

    public string Topic { get; set; } = string.Empty;

    public int DurationMinutes { get; set; }

    public bool IsWeakTopic { get; set; }

    public StudyPlanTaskStatus Status { get; set; } = StudyPlanTaskStatus.Pending;

    public DateTime? CompletedAtUtc { get; set; }

    /// <summary>Null unless this task is a missed-task-recovery replacement — see this class's doc comment.</summary>
    public DateOnly? OriginalScheduledDateUtc { get; set; }

    public StudyPlan? Plan { get; set; }
}
